server:
  port: 8080

# spring相关配置
spring:
  datasource:
    url: jdbc:mysql://${sys_mysql_host}:${sys_mysql_port}/${sys_mysql_database}
    username: ${sys_mysql_username}
    password: ${sys_mysql_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: ${sys_redis_host}
    port: ${sys_redis_port}
    username: ${sys_redis_username}
    password: ${sys_redis_password}
    connect-timeout: 3000
    timeout: 3000

# 第三方相关配置
## 文心一言
ai:
  baidu:
    access_key: ${baidu_access_key}
    secret_key: ${baidu_secret_key}