server:
  port: 8080

# spring相关配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql://192.168.184.135:3306/aurora
  redis:
    host: 192.168.184.135
    database: 1
    port: 6379
    timeout: 3000
    username: default
    password: 12345678

# 第三方相关配置
## 文心一言
ai:
  baidu:
    access_key: 8ef0bd9b8c42423eaf2fae33739d2ca3
    secret_key: 9cc1e409d7ba48bca8e4fe5dc822a39f
logging:
  level:
    org:
      springframework:
        security: debug
        security.web.FilterChainProxy: debug
